### ISSUE TITLE
Error: Don't know how to parse column type: 1009

### ISSUE THREAD

**Issue by rhelenagh** [deno-postgres/deno-postgres#137]
Hello team!
This module for Postgres is very promising. To contribute to its quality, I want to report this error to you:

I have this error because my table contains a property of type text array (text []).

I attach the Stack trace:

`Error: Don't know how to parse column type: 1009
    at decodeText (https://deno.land/x/postgres/decode.ts:233:13)
    at decode (https://deno.land/x/postgres/decode.ts:241:12)
    at QueryResult._parseDataRow (https://deno.land/x/postgres/query.ts:49:24)
    at QueryResult.handleDataRow (https://deno.land/x/postgres/query.ts:61:28)
    at Connection._simpleQuery (https://deno.land/x/postgres/connection.ts:322:18)
    at async Connection.query (https://deno.land/x/postgres/connection.ts:539:16)
    at async Client.query (https://deno.land/x/postgres/client.ts:24:12)
    `

**Comment by hayd** [comment]
closed by #143 !
