### ISSUE TITLE
Some dependency needs deno version 1.2.1 support 

### ISSUE THREAD

**Issue by fauzan121002** [deno-postgres/deno-postgres#157]
I update my deno to version 1.2.1 , while use this package , i got this error , i think you need to upgrade some dependency to support latest deno version.

```
error: Uncaught TypeError: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

Found 2 errors.
```

I hope you fix this issue.

**Comment by fauzan121002** [comment]
I thought it was from the library, I looked for the code that was problematic, apparently nothing was wrong, but the error appeared when I deleted deno-postgres,

my oh my spend 4 hours to fix this issue, with this command:
`deno run -A --unstable --reload server.ts`

I hope this helps if you experience the same thing

**Comment by fauzan121002** [comment]
or you can try this 
`deno cache --unstable --reload <your main file>.ts`

**Comment by fauzan121002** [comment]
I thought it was from the library, I looked for the code that was problematic, apparently nothing was wrong, but the error appeared when I deleted deno-postgres,

my oh my spend 2 hours to fix this issue, with this command:
deno run -A --unstable --reload server.ts "server.ts is my main file"

I hope this helps if you experience the same thing

**Comment by fauzan121002** [comment]
or you can try this
`deno cache --unstable --reload <your main file>.ts`
