### ISSUE TITLE
Error TS2790: The operand of a 'delete' operator must be optional with latest deno-postgres (v0.4.3)

### ISSUE THREAD

**Issue by AzamatbekMamarajabov** [deno-postgres/deno-postgres#163]
I am having such errors with  latest versions of deno@v1.3.2,  ts@v4.0.2, deno-postgres@v0.4.3

```
error: TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.conn;
           ~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:612:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.bufReader;
           ~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:613:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.bufWriter;
           ~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:614:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.packetWriter;
           ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:615:12

Found 4 errors.
```

**Comment by TheWow** [comment]
try this
```javascript
deno upgrade --version 1.3.0
```
and
```javascript
deno run --reload deps.ts
```

**Comment by AzamatbekMamarajabov** [comment]
thanks, it worked, I downgraded typescript, deno-postgres, denon and forgot to downgrade deno, what a coincidence

**Comment by pandakub** [comment]
Note: 0.4.3 of this repos is the most recent release which can be downloaded from Deno's Third Party Modules

0.4.3 has this issue, 0.4.4 does not

https://deno.land/x/postgres@v0.4.3/
