### ISSUE TITLE
TS2790 [ERROR]: The operand of a 'delete' operator must be optional

### ISSUE THREAD

**Issue by pandakub** [deno-postgres/deno-postgres#167]
connection.ts, starting at line 612

I get this error just by importing/exporting DenoDB and running it using the following flags on my Win10 machine through an elevated PowerShell:

E:\<my-deno-apps>\<myapp> deno run --allow-net --allow-env --allow-read=./ entry.ts

error: TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.conn;
           ~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:612:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.bufReader;
           ~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:613:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.bufWriter;
           ~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:614:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.packetWriter;
           ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:615:12

**Comment by pandakub** [comment]
Sorry, this was a duplicate.

**Comment by pandakub** [comment]
Note:  0.4.3 of this repos is the most recent release which can be downloaded from Deno's Third Party Modules

0.4.3 has this issue, 0.4.4 does not

https://deno.land/x/postgres@v0.4.3/
